function cases = symbolic_representability_case_registry()
%SYMBOLIC_REPRESENTABILITY_CASE_REGISTRY Registered constructive demo cases.
%
% Case 1 remains the principal manuscript display. Cases 2 and 3 retain
% representative middle/skip branches, including Coef_M{2,2} and
% Coef_M{3,4}, but are simplified relative to the v73m dense stress tests
% to improve strong-prior BP trainability.

    cases = { ...
        struct( ...
            'id','main_3d_multioutput', ...
            'shortName','Main 3-D multi-output', ...
            'role','main_manuscript_display', ...
            'taskFcn',@task_symbolic_representability_3d, ...
            'compilerFcn',@compile_symbolic_representability_3d), ...
        struct( ...
            'id','moderate_skip_2d_scalar', ...
            'shortName','Moderate-skip 2-D scalar', ...
            'role','middle_branch_learnability_case', ...
            'taskFcn',@task_symbolic_representability_dense_skip_2d, ...
            'compilerFcn',@compile_symbolic_representability_dense_skip_2d), ...
        struct( ...
            'id','moderate_skip_3d_multioutput', ...
            'shortName','Moderate-skip 3-D two-output', ...
            'role','moderate_fanin_fanout_learnability_case', ...
            'taskFcn',@task_symbolic_representability_dense_skip_3d, ...
            'compilerFcn',@compile_symbolic_representability_dense_skip_3d) ...
    };
end
