function resultSR = train_official_pysr_baseline(Xtr, Ytr, Xval, Yval, Xte, Yte, XOod, YOod, task, srOpts, phdnOpts)
%TRAIN_OFFICIAL_PYSR_BASELINE Run official PySR through Python adapter.
%
% The MATLAB side only manages data export/import and metric computation.
% Symbolic regression is performed by the official Python `pysr` package.

    if nargin < 10 || isempty(srOpts)
        srOpts = sr_default_options();
    end
    if nargin < 11
        phdnOpts = [];
    end
    if nargin < 7 || isempty(XOod)
        XOod = zeros(0, size(Xtr, 2));
        YOod = zeros(0, size(Ytr, 2));
    end

    tTotal = tic;
    srDir = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(fileparts(srDir));
    adapterPath = fullfile(srDir, 'pysr_official_adapter.py');
    supervisorPath = fullfile(srDir, 'pysr_matlab_supervisor.py');
    if ~exist(adapterPath, 'file')
        error('Official PySR adapter not found: %s', adapterPath);
    end
    if ~exist(supervisorPath, 'file')
        error('PySR MATLAB supervisor not found: %s', supervisorPath);
    end

    workRoot = getfield_default_local(srOpts, 'workRoot', fullfile(tempdir, 'phdnn_official_pysr_runs'));
    if ~exist(workRoot, 'dir')
        mkdir(workRoot);
    end
    safeCase = regexprep(resolve_case_name_local(task), '[^A-Za-z0-9_\-]', '_');
    runId = sprintf('%s_%s_%06d', safeCase, datestr(now, 'yyyymmdd_HHMMSSFFF'), randi(999999));
    workDir = fullfile(workRoot, runId);
    mkdir(workDir);

    write_matrix_local(fullfile(workDir, 'X_train.csv'), Xtr);
    write_matrix_local(fullfile(workDir, 'Y_train.csv'), Ytr);
    write_matrix_local(fullfile(workDir, 'X_val.csv'), Xval);
    write_matrix_local(fullfile(workDir, 'Y_val.csv'), Yval);
    write_matrix_local(fullfile(workDir, 'X_test.csv'), Xte);
    write_matrix_local(fullfile(workDir, 'Y_test.csv'), Yte);
    write_matrix_local(fullfile(workDir, 'X_ood.csv'), XOod);
    write_matrix_local(fullfile(workDir, 'Y_ood.csv'), YOod);

    pysrPaperRoot = getfield_default_local(srOpts, 'pysrPaperRoot', '');
    if isempty(pysrPaperRoot)
        cand1 = fullfile(projectRoot, 'baselines', 'pysr_paper_main');
        cand2 = fullfile(srDir, 'pysr_paper_main');
        if exist(cand1, 'dir')
            pysrPaperRoot = cand1;
        elseif exist(cand2, 'dir')
            pysrPaperRoot = cand2;
        else
            pysrPaperRoot = '';
        end
    end

    cfg = struct();
    cfg.work_dir = workDir;
    cfg.case_name = resolve_case_name_local(task);
    cfg.variable_names = make_variable_names_local(size(Xtr, 2), task);
    cfg.python_notice = 'This config is generated by MATLAB; official PySRRegressor performs the SR search.';
    cfg.pysr_paper_root = pysrPaperRoot;
    cfg.grammar_casemode = getfield_default_local(srOpts, 'grammarCasemode', 'weak_prior_lv1');
    cfg.niterations = getfield_default_local(srOpts, 'nIterations', 100);
    cfg.populations = getfield_default_local(srOpts, 'populations', 8);
    cfg.multi_output_mode = getfield_default_local(srOpts, 'multiOutputMode', ...
        'native_single_fit_independent_output_archives');
    cfg.population_budget_mode = getfield_default_local(srOpts, 'populationBudgetMode', 'per_output');
    cfg.population_size = getfield_default_local(srOpts, 'populationSize', 50);
    cfg.maxsize = getfield_default_local(srOpts, 'maxSize', 30);
    cfg.maxdepth = getfield_default_local(srOpts, 'maxDepth', 10);
    cfg.parsimony = getfield_default_local(srOpts, 'parsimony', 1e-6);
    cfg.model_selection = getfield_default_local(srOpts, 'modelSelection', 'best');
    cfg.random_state = getfield_default_local(srOpts, 'randomState', 1);
    cfg.deterministic = logical(getfield_default_local(srOpts, 'deterministic', false));
    cfg.parallelism = getfield_default_local(srOpts, 'parallelism', 'multithreading');
    if cfg.deterministic
        cfg.parallelism = 'serial';
    end
    cfg.verbosity = getfield_default_local(srOpts, 'verbosity', 1);
    cfg.progress = logical(getfield_default_local(srOpts, 'progress', false));
    cfg.batching = logical(getfield_default_local(srOpts, 'batching', false));
    cfg.batch_size = max(1, round(getfield_default_local(srOpts, 'batchSize', 50)));
    % These controls are optional and are emitted only when the calling case
    % explicitly provides them. ncycles_per_iteration is intentionally absent.
    if isfield(srOpts,'tournamentSelectionN') && ...
            ~isempty(srOpts.tournamentSelectionN)
        cfg.tournament_selection_n = max(1,round(srOpts.tournamentSelectionN));
    end
    if isfield(srOpts,'tournamentSelectionP') && ...
            ~isempty(srOpts.tournamentSelectionP)
        cfg.tournament_selection_p = min(1,max(eps,double(srOpts.tournamentSelectionP)));
    end
    if isfield(srOpts,'annealing') && ~isempty(srOpts.annealing)
        cfg.annealing = logical(srOpts.annealing);
    end
    if isfield(srOpts,'annealingAlpha') && ~isempty(srOpts.annealingAlpha)
        cfg.annealing_alpha = max(eps,double(srOpts.annealingAlpha));
    end
    if isfield(srOpts,'crossoverProbability') && ...
            ~isempty(srOpts.crossoverProbability)
        cfg.crossover_probability = min(1,max(0,double(srOpts.crossoverProbability)));
    end
    if isfield(srOpts,'weightOptimize') && ~isempty(srOpts.weightOptimize)
        cfg.weight_optimize = max(0,double(srOpts.weightOptimize));
    end
    growthWeightMap = { ...
        'weightAddNode','weight_add_node'; ...
        'weightInsertNode','weight_insert_node'; ...
        'weightDeleteNode','weight_delete_node'; ...
        'weightDoNothing','weight_do_nothing'; ...
        'weightMutateConstant','weight_mutate_constant'; ...
        'weightMutateOperator','weight_mutate_operator'; ...
        'weightMutateFeature','weight_mutate_feature'; ...
        'weightSwapOperands','weight_swap_operands'; ...
        'weightRotateTree','weight_rotate_tree'; ...
        'weightRandomize','weight_randomize'; ...
        'weightSimplify','weight_simplify'};
    for iGrowthWeight = 1:size(growthWeightMap,1)
        matlabName = growthWeightMap{iGrowthWeight,1};
        jsonName = growthWeightMap{iGrowthWeight,2};
        if isfield(srOpts,matlabName) && ~isempty(srOpts.(matlabName))
            cfg.(jsonName) = max(0,double(srOpts.(matlabName)));
        end
    end
    if isfield(srOpts,'optimizeProbability') && ~isempty(srOpts.optimizeProbability)
        cfg.optimize_probability = min(1,max(0,double(srOpts.optimizeProbability)));
    end
    if isfield(srOpts,'shouldSimplify') && ~isempty(srOpts.shouldSimplify)
        cfg.should_simplify = logical(srOpts.shouldSimplify);
    end
    cfg.minimum_pysr_version = char(string(getfield_default_local( ...
        srOpts, 'minimumPySRVersion', '2.0.0a2')));
    cfg.require_pysr2 = logical(getfield_default_local(srOpts, 'requirePySR2', true));
    requestedInitialGuessesEnable = logical(getfield_default_local( ...
        srOpts, 'initialGuessesEnable', false));
    cfg.initial_guesses = normalize_string_cell_local(getfield_default_local( ...
        srOpts, 'initialGuesses', {}));
    % Empty is the documented no-prior setting. Never emit an inconsistent
    % JSON configuration with enable=true and an empty guess library.
    cfg.initial_guesses_enable = requestedInitialGuessesEnable && ...
        ~isempty(cfg.initial_guesses);
    cfg.fraction_replaced_guesses = getfield_default_local( ...
        srOpts, 'fractionReplacedGuesses', 0.05);
    requestedInitialGuessScope = char(string(getfield_default_local( ...
        srOpts, 'initialGuessScope', 'shared_all_unresolved_outputs')));
    % Backward-compatible rescue alias normalization.  Targeted rescue runs are
    % single-output PySR fits; after the MATLAB controller subsets the guess
    % library, the official canonical scope is still shared_all_unresolved_outputs
    % because there is exactly one unresolved output.  Normalize the short-lived
    % legacy token here so stale callers cannot crash the Python adapter.
    if strcmpi(strtrim(requestedInitialGuessScope),'single_output_rescue')
        cfg.initial_guess_scope = 'shared_all_unresolved_outputs';
    else
        cfg.initial_guess_scope = requestedInitialGuessScope;
    end
    cfg.machine_precision_early_stop_enable = logical(getfield_default_local( ...
        srOpts, 'machinePrecisionEarlyStopEnable', false));
    cfg.machine_precision_early_stop_abs_mse = max(0, getfield_default_local( ...
        srOpts, 'machinePrecisionEarlyStopAbsMSE', 1e-12));
    cfg.machine_precision_early_stop_rel_mse = max(0, getfield_default_local( ...
        srOpts, 'machinePrecisionEarlyStopRelMSE', 1e-12));
    cfg.machine_precision_early_stop_check_interval = max(1, round(getfield_default_local( ...
        srOpts, 'machinePrecisionEarlyStopCheckInterval', 50)));
    cfg.machine_precision_early_stop_min_iterations = max(1, round(getfield_default_local( ...
        srOpts, 'machinePrecisionEarlyStopMinIterations', ...
        cfg.machine_precision_early_stop_check_interval)));
    cfg.binary_operators = normalize_operator_list_local(getfield_default_local(srOpts, 'binaryOperators', {'+', '-', '*', '/'}), cfg.grammar_casemode, false);
    cfg.unary_operators = normalize_operator_list_local(getfield_default_local(srOpts, 'unaryOperators', {'inv', 'sqrt'}), cfg.grammar_casemode, true);

    % Case-local typed physical grammar for the known SMIB state identities.
    % Fixed machine/network parameters may be absorbed into fitted constants,
    % so state-dependent division/inversion is neither physically required nor
    % numerically admissible in this case.  The Python adapter additionally
    % validates case-local trigonometric and denominator rules before selection.
    caseSupportsTypedPrior = is_single_generator_dynamic_case_local(task);
    typedPriorMode = char(string(getfield_default_local( ...
        srOpts,'typedPhysicalConstraints','')));
    typedPriorEnable = ~isempty(strtrim(typedPriorMode));
    if ~typedPriorEnable && caseSupportsTypedPrior
        typedPriorMode = 'single_generator_dynamic';
        typedPriorEnable = true;
    end
    if typedPriorEnable
        if ~caseSupportsTypedPrior
            error(['Typed generator physical constraints were requested for an ', ...
                'unrecognized task.']);
        end
        cfg.typed_physical_constraints = typedPriorMode;
        if logical(getfield_default_local(srOpts,'forbidStateDependentDivision',true))
            cfg.binary_operators = cfg.binary_operators(~strcmp(cfg.binary_operators, '/'));
            cfg.unary_operators = cfg.unary_operators(~strcmpi(cfg.unary_operators, 'inv'));
        end
        cfg.trig_allowed_variables = getfield_default_local( ...
            srOpts,'trigAllowedVariables',{'x1'});
        cfg.strict_trig_atoms_only = logical(getfield_default_local( ...
            srOpts,'strictTrigAtomsOnly',true));
        cfg.original_output_indices = getfield_default_local( ...
            srOpts,'originalOutputIndices',[]);
    else
        cfg.typed_physical_constraints = '';
    end
    cfg.operator_complexities = getfield_default_local(srOpts, 'operatorComplexities', struct());
    cfg.forbid_nested_trig = logical(getfield_default_local(srOpts, 'forbidNestedTrig', false));
    cfg.forbid_nested_square = logical(getfield_default_local(srOpts, 'forbidNestedSquare', false));
    cfg.forbid_nested_sqrt = logical(getfield_default_local(srOpts, 'forbidNestedSqrt', false));
    cfg.forbid_motif_reverse_nesting = logical(getfield_default_local(srOpts, 'forbidMotifReverseNesting', false));
    cfg.max_operator_occurrences = getfield_default_local(srOpts, 'maxOperatorOccurrences', struct());
    cfg.top_k_expressions_to_report = getfield_default_local(srOpts, 'topKExpressionsToReport', 10);
    cfg.display_candidate_rankings = logical(getfield_default_local(srOpts, 'displayCandidateRankings', false));
    cfg.candidate_ranking_top_k = max(0, round(getfield_default_local(srOpts, 'candidateRankingTopK', 20)));
    cfg.equation_loss_multiplier = getfield_default_local(srOpts, 'equationLossMultiplier', 10);
    cfg.max_report_complexity = getfield_default_local(srOpts, 'maxReportComplexity', 1000);
    cfg.semantic_dedup_tolerance = getfield_default_local(srOpts, 'semanticDedupTolerance', 1e-8);
    cfg.selection_policy = char(string(getfield_default_local(srOpts, 'selectionPolicy', 'pysr_native_score')));
    cfg.structure_score_enable = logical(getfield_default_local(srOpts, 'structureScoreEnable', false));
    cfg.structure_validation_multiplier = getfield_default_local(srOpts, 'structureValidationMultiplier', 4.0);
    cfg.structure_validation_weight = getfield_default_local(srOpts, 'structureValidationWeight', 0.20);
    cfg.structure_machine_error_abs_mse_floor = getfield_default_local( ...
        srOpts, 'structureMachineErrorAbsMSEFloor', 0);
    cfg.structure_machine_error_rel_mse_floor = getfield_default_local( ...
        srOpts, 'structureMachineErrorRelMSEFloor', 0);
    cfg.structure_neighborhood_max_distance = getfield_default_local(srOpts, 'structureNeighborhoodMaxDistance', 0.55);
    cfg.structure_neighborhood_min_distance = getfield_default_local(srOpts, 'structureNeighborhoodMinDistance', 0.10);
    cfg.structure_neighborhood_complexity_window = getfield_default_local(srOpts, 'structureNeighborhoodComplexityWindow', 8);
    cfg.structure_frontier_max_abs = getfield_default_local(srOpts, 'structureFrontierMaxAbs', 20);
    cfg.paths = struct();
    cfg.paths.X_train = fullfile(workDir, 'X_train.csv');
    cfg.paths.Y_train = fullfile(workDir, 'Y_train.csv');
    cfg.paths.X_val = fullfile(workDir, 'X_val.csv');
    cfg.paths.Y_val = fullfile(workDir, 'Y_val.csv');
    cfg.paths.X_test = fullfile(workDir, 'X_test.csv');
    cfg.paths.Y_test = fullfile(workDir, 'Y_test.csv');
    cfg.paths.X_ood = fullfile(workDir, 'X_ood.csv');
    cfg.paths.Y_ood = fullfile(workDir, 'Y_ood.csv');

    configPath = fullfile(workDir, 'config.json');
    fid = fopen(configPath, 'w');
    if fid < 0
        error('Cannot write PySR config: %s', configPath);
    end
    fwrite(fid, jsonencode(cfg, 'PrettyPrint', true), 'char');
    fclose(fid);

    pythonExe = getfield_default_local(srOpts, 'pythonExe', 'python');

    % v72c bugfix: launch an independent supervisor which remains responsive while
    % the real adapter is blocked inside PySR model.fit(). The supervisor
    % records and owns the exact adapter PID for this run only.
    matlabPid = feature('getpid');
    controlPath = fullfile(workDir, 'matlab_run_alive.flag');
    adapterPidPath = fullfile(workDir, 'adapter_pid.txt');
    write_text_file_local(controlPath, sprintf('MATLAB_PID=%d\nRUN_ID=%s\n', matlabPid, runId));
    supervisorArgs = {'--python', pythonExe, '--adapter', adapterPath, ...
        '--config', configPath, '--parent-pid', num2str(matlabPid), ...
        '--control-file', controlPath, '--adapter-pid-file', adapterPidPath};
    cmd = format_command_for_display_local(pythonExe, supervisorPath, supervisorArgs);
    stdoutPath = fullfile(workDir, 'matlab_python_stdout.txt');
    tCall = tic;
    [status, cmdout, processInfo] = run_external_process_guarded( ...
        pythonExe, [{supervisorPath}, supervisorArgs], stdoutPath, ...
        configPath, controlPath, adapterPidPath);
    callTime = toc(tCall);
    if status ~= 0
        error(['Official PySR baseline failed with status %d.\nCommand: %s\n', ...
            'Adapter PID: %.0f\nOutput:\n%s\nWork dir: %s'], ...
            status, cmd, processInfo.adapterPid, cmdout, workDir);
    end

    resultPath = fullfile(workDir, 'result.json');
    if ~exist(resultPath, 'file')
        error('Official PySR adapter did not create result.json. Work dir: %s\nOutput:\n%s', workDir, cmdout);
    end
    pyResult = jsondecode(fileread(resultPath));

    YhatTr = read_matrix_local(fullfile(workDir, 'Yhat_train.csv'));
    YhatVal = read_matrix_local(fullfile(workDir, 'Yhat_val.csv'));
    YhatTe = read_matrix_local(fullfile(workDir, 'Yhat_test.csv'));
    if size(YhatTr, 2) ~= size(Ytr, 2) && size(YhatTr, 1) == size(Ytr, 2)
        YhatTr = YhatTr.';
    end
    if size(YhatVal, 2) ~= size(Yval, 2) && size(YhatVal, 1) == size(Yval, 2)
        YhatVal = YhatVal.';
    end
    if size(YhatTe, 2) ~= size(Yte, 2) && size(YhatTe, 1) == size(Yte, 2)
        YhatTe = YhatTe.';
    end

    if ~isempty(XOod)
        YhatOod = read_matrix_local(fullfile(workDir, 'Yhat_ood.csv'));
        if size(YhatOod, 2) ~= size(YOod, 2) && size(YhatOod, 1) == size(YOod, 2)
            YhatOod = YhatOod.';
        end
        oodMetrics = compute_regression_metrics(YhatOod, YOod);
    else
        YhatOod = [];
        oodMetrics = struct('mse', NaN, 'rmse', NaN);
    end

    resultSR = struct();
    resultSR.method = 'official_pysr';
    resultSR.searchBackend = 'official_pysr';
    resultSR.searchMethod = 'official_pysr_regressor_native_multioutput';
    resultSR.reportRole = getfield_default_local(srOpts, 'reportRole', 'independent_sr_baseline');
    resultSR.reportTitle = getfield_default_local(srOpts, 'reportTitle', 'Official PySR engine result');
    resultSR.dictionarySource = sprintf('Official PySR operators from grammar casemode %s', cfg.grammar_casemode);
    resultSR.grammarCasemode = cfg.grammar_casemode;
    resultSR.variableIndexBase = getfield_default_local(pyResult, 'variable_index_base', 1);
    resultSR.multiOutputMode = getfield_default_local(pyResult, 'multi_output_mode', '');
    resultSR.multiOutputStats = getfield_default_local(pyResult, 'multi_output_stats', struct());
    resultSR.machinePrecisionEarlyStop = getfield_default_local( ...
        pyResult, 'machine_precision_early_stop', struct());
    resultSR.machinePrecisionEarlyStopEnabled = logical(getfield_default_local( ...
        pyResult, 'machine_precision_early_stop_enabled', ...
        cfg.machine_precision_early_stop_enable));
    resultSR.machinePrecisionEarlyStopTriggered = logical(getfield_default_local( ...
        pyResult, 'machine_precision_early_stop_triggered', false));
    resultSR.nIterationsRequested = getfield_default_local( ...
        pyResult, 'niterations_requested', cfg.niterations);
    resultSR.nIterationsCompleted = getfield_default_local( ...
        pyResult, 'niterations_completed', cfg.niterations);
    resultSR.pysrVersion = getfield_default_local(pyResult, 'pysr_version', '');
    resultSR.initialGuessesEnabled = logical(getfield_default_local( ...
        pyResult, 'initial_guesses_enabled', cfg.initial_guesses_enable));
    resultSR.initialGuesses = getfield_default_local( ...
        pyResult, 'initial_guesses', cfg.initial_guesses);
    resultSR.fractionReplacedGuesses = getfield_default_local( ...
        pyResult, 'fraction_replaced_guesses', cfg.fraction_replaced_guesses);
    resultSR.periodicGuessReinjectionEnabled = logical(getfield_default_local( ...
        pyResult, 'periodic_guess_reinjection_enabled', ...
        cfg.initial_guesses_enable && cfg.fraction_replaced_guesses > 0));
    resultSR.guessInjectionPolicy = char(string(getfield_default_local( ...
        pyResult, 'guess_injection_policy', ...
        'official_periodic_population_replacement')));
    resultSR.initialGuessScope = getfield_default_local( ...
        pyResult, 'initial_guess_scope', cfg.initial_guess_scope);
    resultSR.batching = logical(getfield_default_local(pyResult, 'batching', cfg.batching));
    resultSR.evolutionControls = getfield_default_local( ...
        pyResult, 'evolution_controls', struct());
    resultSR.requestedBatchSize = getfield_default_local(pyResult, ...
        'requested_batch_size', cfg.batch_size);
    resultSR.effectiveBatchSize = getfield_default_local(pyResult, ...
        'effective_batch_size', min(cfg.batch_size, size(Xtr,1)));
    resultSR.pythonExe = pythonExe;
    resultSR.pysrPaperRoot = pysrPaperRoot;
    resultSR.workDir = workDir;
    resultSR.configPath = configPath;
    resultSR.resultJsonPath = resultPath;
    resultSR.stdoutPath = stdoutPath;
    resultSR.equationsFiles = collect_equations_files_local(pyResult);
    resultSR.expression = collect_expressions_local(pyResult);
    resultSR.expressions = resultSR.expression;
    resultSR.bestScoreExpressionsPerOutput = collect_selected_expressions_local(pyResult, 'selected_core');
    resultSR.coreExpressionsPerOutput = resultSR.bestScoreExpressionsPerOutput;
    % Backward-compatible alias: Stage 0 still exports one selected core only.
    resultSR.bestExpressionsPerOutput = resultSR.bestScoreExpressionsPerOutput;
    resultSR.outputSelections = collect_output_selections_local(pyResult);
    resultSR.candidateRankingsByValidation = collect_candidate_rankings_local(pyResult, 'external_validation_ranked_by_mse');
    resultSR.candidateRankingsByComplexity = collect_candidate_rankings_local(pyResult, 'external_validation_ranked_by_complexity');
    resultSR.candidateRankingsByBestScore = collect_candidate_rankings_local(pyResult, 'external_validation_ranked_by_best_score');
    resultSR.candidateRankingsByStructureScore = collect_candidate_rankings_local(pyResult, 'external_validation_ranked_by_structure_score');
    resultSR.topExpressionsByLoss = collect_top_expressions_local(pyResult, 'top_expressions_by_loss');
    resultSR.topExpressionsByScore = collect_top_expressions_local(pyResult, 'top_expressions_by_score');
    resultSR.topExpressions = resultSR.topExpressionsByLoss;  % backward-compatible alias
    resultSR.nActiveCoefficients = extract_max_complexity_local(pyResult);
    resultSR.complexity = resultSR.nActiveCoefficients;
    resultSR.trainMetrics = compute_regression_metrics(YhatTr, Ytr);
    resultSR.valMetrics = compute_regression_metrics(YhatVal, Yval);
    resultSR.validationMSE = resultSR.valMetrics.mse;
    resultSR.testMetrics = compute_regression_metrics(YhatTe, Yte);
    resultSR.oodMetrics = oodMetrics;
    resultSR.YhatTrain = YhatTr;
    resultSR.YhatVal = YhatVal;
    resultSR.YhatTest = YhatTe;
    resultSR.YhatOod = YhatOod;
    resultSR.trainTime = getfield_default_local(pyResult, 'total_time_seconds', toc(tTotal));
    resultSR.timeStats = struct();
    resultSR.timeStats.total = toc(tTotal);
    resultSR.timeStats.pythonCallTime = callTime;
    resultSR.timeStats.pyTotalTime = getfield_default_local(pyResult, 'total_time_seconds', NaN);
    resultSR.timeStats.exportImportTime = resultSR.timeStats.total - callTime;
    resultSR.pyResult = pyResult;
    resultSR.opts = srOpts;
end

function write_matrix_local(path, A)
    if isempty(A)
        fid = fopen(path, 'w');
        fclose(fid);
        return;
    end
    if exist('writematrix', 'file') == 2
        writematrix(A, path);
    else
        csvwrite(path, A);
    end
end

function A = read_matrix_local(path)
    if ~exist(path, 'file') || dir(path).bytes == 0
        A = [];
        return;
    end
    if exist('readmatrix', 'file') == 2
        A = readmatrix(path);
    else
        A = csvread(path);
    end
    if isvector(A)
        A = A(:);
    end
end

function names = make_variable_names_local(nx, task)
    if isfield(task, 'variableNames') && numel(task.variableNames) >= nx
        names = task.variableNames(1:nx);
    else
        names = arrayfun(@(i) sprintf('x%d', i), 1:nx, 'UniformOutput', false);
    end
end

function ops = normalize_operator_list_local(x, grammarCasemode, isUnary)
    if nargin < 2 || isempty(grammarCasemode)
        grammarCasemode = 'weak_prior_lv1';
    end
    if nargin < 3
        isUnary = false;
    end
    if ischar(x) || (isstring(x) && isscalar(x))
        xs = char(x);
        if strcmpi(strtrim(xs), 'auto')
            if isUnary
                if strcmpi(strtrim(grammarCasemode), 'general')
                    ops = {'square', 'cube', 'inv', 'sqrt', 'exp', 'sin', 'cos'};
                else
                    ops = {'inv', 'sqrt'};
                end
            else
                ops = {'+', '-', '*', '/'};
            end
        else
            parts = regexp(xs, '[,; ]+', 'split');
            ops = parts(~cellfun(@isempty, parts));
        end
    elseif isstring(x)
        ops = cellstr(x);
    elseif iscell(x)
        ops = x;
    else
        if isUnary
            ops = {'inv', 'sqrt'};
        else
            ops = {'+', '-', '*', '/'};
        end
    end
end

function caseName = resolve_case_name_local(task)
    if isfield(task, 'caseName') && ~isempty(task.caseName)
        caseName = task.caseName;
        return;
    end
    if isfield(task, 'name') && ~isempty(task.name)
        caseName = regexprep(task.name, '^KAN_Feynman_', '');
        return;
    end
    caseName = 'unknown_case';
end

function expressions = collect_selected_expressions_local(pyResult, fieldName)
    expressions = {};
    if ~isstruct(pyResult) || ~isfield(pyResult, 'outputs') || ~isstruct(pyResult.outputs)
        return;
    end
    outs = pyResult.outputs;
    expressions = cell(1, numel(outs));
    for i = 1:numel(outs)
        expressions{i} = '';
        if isfield(outs(i), fieldName) && isstruct(outs(i).(fieldName)) && ...
                isfield(outs(i).(fieldName), 'expression')
            expressions{i} = char(outs(i).(fieldName).expression);
        elseif any(strcmp(fieldName, {'selected_core','selected_best_score','selected_best'})) && isfield(outs(i), 'expression')
            expressions{i} = char(outs(i).expression);
        end
    end
end

function selections = collect_output_selections_local(pyResult)
    selections = struct([]);
    if ~isstruct(pyResult) || ~isfield(pyResult, 'outputs') || ~isstruct(pyResult.outputs)
        return;
    end
    outs = pyResult.outputs;
    selections = repmat(struct('outputIndex',NaN,'core',struct(),'bestScore',struct(), ...
        'best',struct(),'candidates',struct([]),'validationRanking',struct([]), ...
        'complexityRanking',struct([]),'bestScoreRanking',struct([]), ...
        'structureScoreRanking',struct([]), ...
        'candidateCount',0,'selectionMode','pysr_native_score'), 1, numel(outs));
    for i = 1:numel(outs)
        selections(i).outputIndex = getfield_default_local(outs(i), 'output_index', i);
        selections(i).core = getfield_default_local(outs(i), 'selected_core', struct());
        selections(i).bestScore = getfield_default_local(outs(i), 'selected_best_score', selections(i).core);
        % Backward-compatible alias only; there is no separate simple candidate.
        selections(i).best = selections(i).core;
        selections(i).selectionMode = char(string(getfield_default_local(outs(i), 'selection_mode', 'pysr_native_score')));
        selections(i).candidates = getfield_default_local(outs(i), 'compile_fallback_candidates', struct([]));
        selections(i).validationRanking = getfield_default_local(outs(i), 'external_validation_ranked_by_mse', struct([]));
        selections(i).complexityRanking = getfield_default_local(outs(i), 'external_validation_ranked_by_complexity', struct([]));
        selections(i).bestScoreRanking = getfield_default_local(outs(i), 'external_validation_ranked_by_best_score', struct([]));
        selections(i).structureScoreRanking = getfield_default_local(outs(i), 'external_validation_ranked_by_structure_score', struct([]));
        selections(i).candidateCount = getfield_default_local(outs(i), 'external_validation_candidate_count', 0);
    end
end

function rankings = collect_candidate_rankings_local(pyResult, fieldName)
    % MATLAB struct-array assignment requires every element to have exactly
    % the same field set and field order.  The JSON candidate rows may omit
    % optional PySR metadata such as loss or score on individual equations,
    % so assigning the decoded rows directly can raise:
    %   "Subscripted assignment between dissimilar structures."
    % Normalize every row into one fixed schema before appending it.
    template = candidate_ranking_template_local();
    rankings = repmat(template, 1, 0);
    if ~isstruct(pyResult) || ~isfield(pyResult, 'outputs') || ~isstruct(pyResult.outputs)
        return;
    end
    outs = pyResult.outputs;
    for i = 1:numel(outs)
        rows = getfield_default_local(outs(i), fieldName, struct([]));
        outputIndex = getfield_default_local(outs(i), 'output_index', i);
        if isstruct(rows)
            for j = 1:numel(rows)
                rankings(end+1) = normalize_candidate_ranking_row_local(rows(j), outputIndex); %#ok<AGROW>
            end
        elseif iscell(rows)
            % Defensive path for MATLAB releases that decode heterogeneous
            % JSON object arrays as cell arrays rather than struct arrays.
            for j = 1:numel(rows)
                if isstruct(rows{j})
                    rankings(end+1) = normalize_candidate_ranking_row_local(rows{j}, outputIndex); %#ok<AGROW>
                end
            end
        end
    end
end

function row = candidate_ranking_template_local()
    row = struct( ...
        'outputIndex', NaN, ...
        'rank', NaN, ...
        'rank_mode', '', ...
        'table_position', NaN, ...
        'table_index', '', ...
        'expression', '', ...
        'complexity', NaN, ...
        'train_mse', NaN, ...
        'validation_mse', NaN, ...
        'relative_to_best_validation_mse', NaN, ...
        'ranking_scope', '', ...
        'relative_error_scope', '', ...
        'selection_role', 'none', ...
        'loss', NaN, ...
        'score', NaN, ...
        'structure_signature', '', ...
        'structure_eligible', false, ...
        'frontier_score_raw', NaN, ...
        'frontier_score_valid', false, ...
        'frontier_score_normalized', NaN, ...
        'validation_soft_score', NaN, ...
        'structure_score', NaN);
end

function row = normalize_candidate_ranking_row_local(sourceRow, outputIndex)
    row = candidate_ranking_template_local();
    row.outputIndex = outputIndex;
    if ~isstruct(sourceRow)
        return;
    end
    row.rank = getfield_default_local(sourceRow, 'rank', NaN);
    row.rank_mode = char(string(getfield_default_local(sourceRow, 'rank_mode', '')));
    row.table_position = getfield_default_local(sourceRow, 'table_position', NaN);
    row.table_index = char(string(getfield_default_local(sourceRow, 'table_index', '')));
    row.expression = char(string(getfield_default_local(sourceRow, 'expression', '')));
    row.complexity = getfield_default_local(sourceRow, 'complexity', NaN);
    row.train_mse = getfield_default_local(sourceRow, 'train_mse', NaN);
    row.validation_mse = getfield_default_local(sourceRow, 'validation_mse', NaN);
    row.relative_to_best_validation_mse = getfield_default_local( ...
        sourceRow, 'relative_to_best_validation_mse', NaN);
    row.ranking_scope = char(string(getfield_default_local(sourceRow, 'ranking_scope', '')));
    row.relative_error_scope = char(string(getfield_default_local( ...
        sourceRow, 'relative_error_scope', '')));
    row.selection_role = char(string(getfield_default_local(sourceRow, 'selection_role', 'none')));
    row.loss = getfield_default_local(sourceRow, 'loss', NaN);
    row.score = getfield_default_local(sourceRow, 'score', NaN);
    row.structure_signature = char(string(getfield_default_local(sourceRow, 'structure_signature', '')));
    row.structure_eligible = logical(getfield_default_local(sourceRow, 'structure_eligible', false));
    row.frontier_score_raw = getfield_default_local(sourceRow, 'frontier_score_raw', NaN);
    row.frontier_score_valid = logical(getfield_default_local(sourceRow, 'frontier_score_valid', false));
    row.frontier_score_normalized = getfield_default_local(sourceRow, 'frontier_score_normalized', NaN);
    row.validation_soft_score = getfield_default_local(sourceRow, 'validation_soft_score', NaN);
    row.structure_score = getfield_default_local(sourceRow, 'structure_score', NaN);
end

function files = collect_equations_files_local(pyResult)
    files = {};
    if isstruct(pyResult) && isfield(pyResult, 'outputs')
        outs = pyResult.outputs;
        if isstruct(outs)
            for i = 1:numel(outs)
                if isfield(outs(i), 'equations_csv')
                    files{end+1} = outs(i).equations_csv; %#ok<AGROW>
                end
            end
        end
    end
end

function expr = collect_expressions_local(pyResult)
    expr = '';
    if isstruct(pyResult) && isfield(pyResult, 'outputs')
        outs = pyResult.outputs;
        if isstruct(outs)
            parts = cell(1, numel(outs));
            for i = 1:numel(outs)
                if isfield(outs(i), 'expression')
                    parts{i} = char(outs(i).expression);
                else
                    parts{i} = '';
                end
            end
            if numel(parts) == 1
                expr = parts{1};
            else
                labeled = cell(1, numel(parts));
                for i = 1:numel(parts)
                    labeled{i} = sprintf('y%d = %s', i, parts{i});
                end
                expr = strjoin(labeled, '; ');
            end
        end
    end
end


function topExpr = collect_top_expressions_local(pyResult, fieldName)
    topExpr = struct([]);
    if nargin < 2 || isempty(fieldName)
        fieldName = 'top_expressions';
    end
    if ~isstruct(pyResult) || ~isfield(pyResult, 'outputs')
        return;
    end
    outs = pyResult.outputs;
    if ~isstruct(outs)
        return;
    end
    iRow = 0;
    for i = 1:numel(outs)
        if ~isfield(outs(i), fieldName) || isempty(outs(i).(fieldName))
            continue;
        end
        rows = outs(i).(fieldName);
        if ~isstruct(rows)
            continue;
        end
        for j = 1:numel(rows)
            iRow = iRow + 1;
            topExpr(iRow).outputIndex = getfield_default_local(outs(i), 'output_index', i); %#ok<AGROW>
            topExpr(iRow).rank = getfield_default_local(rows(j), 'rank', j);
            topExpr(iRow).complexity = getfield_default_local(rows(j), 'complexity', NaN);
            topExpr(iRow).loss = getfield_default_local(rows(j), 'loss', NaN);
            topExpr(iRow).score = getfield_default_local(rows(j), 'score', NaN);
            if isfield(rows(j), 'expression') && ~isempty(rows(j).expression)
                topExpr(iRow).expression = char(rows(j).expression);
            else
                topExpr(iRow).expression = '<expression unavailable>';
            end
        end
    end
end

function c = extract_max_complexity_local(pyResult)
    c = NaN;
    vals = [];
    if isstruct(pyResult) && isfield(pyResult, 'outputs')
        outs = pyResult.outputs;
        if isstruct(outs)
            for i = 1:numel(outs)
                if isfield(outs(i), 'complexity') && isnumeric(outs(i).complexity)
                    vals(end+1) = outs(i).complexity; %#ok<AGROW>
                end
            end
        end
    end
    if ~isempty(vals)
        c = max(vals);
    end
end


function out = normalize_string_cell_local(value)
%NORMALIZE_STRING_CELL_LOCAL Convert char/string/cell input to a row cellstr.
    if isempty(value)
        out = {};
    elseif ischar(value)
        out = {value};
    elseif isstring(value)
        out = cellstr(value(:).');
    elseif iscell(value)
        out = cellfun(@(x) char(string(x)), value(:).', 'UniformOutput', false);
        out = out(~cellfun(@isempty, strtrim(out)));
    else
        error('Initial PySR guesses must be char, string, or cell array of strings.');
    end
end

function val = getfield_default_local(s, name, defaultVal)
    if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
        val = s.(name);
    else
        val = defaultVal;
    end
end


function cmd = format_command_for_display_local(pythonExe, guardPath, guardArgs)
    parts = [{pythonExe}, {guardPath}, guardArgs];
    for k = 1:numel(parts)
        value = char(parts{k});
        value = strrep(value, '"', '\"');
        parts{k} = ['"', value, '"'];
    end
    cmd = strjoin(parts, ' ');
end

function write_text_file_local(path, text)
    fid = fopen(path, 'w');
    if fid < 0; error('Cannot write control file: %s', path); end
    cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fwrite(fid, text, 'char');
end

function tf = is_single_generator_dynamic_case_local(task)
    tf = false;
    if ~isstruct(task)
        return;
    end
    names = {};
    for fieldName = {'name','caseId','modelVariant'}
        f = fieldName{1};
        if isfield(task,f) && ~isempty(task.(f))
            names{end+1} = lower(char(string(task.(f)))); %#ok<AGROW>
        end
    end
    if isfield(task,'parameters') && isstruct(task.parameters) && ...
            isfield(task.parameters,'modelVariant')
        names{end+1} = lower(char(string(task.parameters.modelVariant))); %#ok<AGROW>
    end
    joined = strjoin(names,' ');
    tf = contains(joined,'singlegeneratordynamic') || ...
        contains(joined,'single_generator_dynamic') || ...
        contains(joined,'smib_avr') || contains(joined,'salient_pole');
end
