function terms = branch_dictionary_terms(inputDim, arch, varPrefix, layerIndex, branchIndex)
%BRANCH_DICTIONARY_TERMS Metadata for explicit case-specific dictionary terms.
%
% previous-version: terms are not generated by a broad polynomial/operator/cross recipe;
% they are listed by the task/case dictionary.
	if nargin < 3 || isempty(varPrefix)
		varPrefix = 'h';
	end
	if nargin < 4
		layerIndex = [];
	end
	if nargin < 5
		branchIndex = [];
	end
	names = explicit_case_dictionary_terms(inputDim, arch, layerIndex, branchIndex);
	terms = struct('index', {}, 'name', {}, 'type', {}, 'exponent', {}, 'opName', {}, 'leftIndex', {}, 'rightIndex', {}, 'isIdentityCancellation', {});
	for k = 1:numel(names)
		name = convert_prefix_local(names{k}, varPrefix, inputDim);
		[typeName, opName] = infer_type_local(name);
		terms(k) = struct('index', k, 'name', name, 'type', typeName, 'exponent', [], ...
			'opName', opName, 'leftIndex', NaN, 'rightIndex', NaN, 'isIdentityCancellation', false); %#ok<AGROW>
	end
end

function out = convert_prefix_local(name, prefix, inputDim)
	out = char(name);
	for kk = inputDim:-1:1
		out = regexprep(out, sprintf('(?<![A-Za-z0-9_])v%d(?![A-Za-z0-9_])', kk), sprintf('%s%d', prefix, kk));
	end
end

function [typeName, opName] = infer_type_local(name)
	opName = '';
	if strcmp(name, '1')
		typeName = 'constant'; return;
	end
	m = regexp(name, '^(inv|sqrt|exp|sin|cos|asin|log)\(', 'tokens', 'once');
	if ~isempty(m)
		typeName = 'op'; opName = m{1}; return;
	end
	m = regexp(name, '\*(inv|sqrt|exp|sin|cos|asin|log)\(', 'tokens', 'once');
	if ~isempty(m)
		typeName = 'cross'; opName = m{1}; return;
	end
	typeName = 'poly';
end
